spring:
  application:
    name: wallet-service

  # Общие настройки для всех профилей
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Профиль по умолчанию при локальном запуске
  profiles:
    active: local

---
# Локальный профиль
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_user
    password: wallet_pass

---
# DOCKER профиль
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wallet_db}
    username: ${POSTGRES_USER:wallet_user}
    password: ${POSTGRES_PASSWORD:wallet_pass}